/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author ll
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_mantenimiento = new javax.swing.JMenu();
        mn_medico = new javax.swing.JMenu();
        mn_consultame = new javax.swing.JMenuItem();
        mn_registrome = new javax.swing.JMenuItem();
        mn_centromedico = new javax.swing.JMenu();
        mn_consultacm = new javax.swing.JMenuItem();
        mn_registrocm = new javax.swing.JMenuItem();
        mn_empleado = new javax.swing.JMenu();
        mn_consultaem = new javax.swing.JMenuItem();
        mn_registroem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_consultafecha = new javax.swing.JMenuItem();
        mn_consultaempleado = new javax.swing.JMenuItem();
        mn_consultaunidad = new javax.swing.JMenuItem();
        mn_consultamotivo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mn_registrodescansomedico = new javax.swing.JMenuItem();
        mn_consultadescansomedicodetallada = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Principal");

        mn_mantenimiento.setBackground(new java.awt.Color(102, 102, 102));
        mn_mantenimiento.setForeground(new java.awt.Color(0, 0, 204));
        mn_mantenimiento.setText("Mantenimiento");

        mn_medico.setText("Medico");

        mn_consultame.setText("Consulta");
        mn_consultame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultameActionPerformed(evt);
            }
        });
        mn_medico.add(mn_consultame);

        mn_registrome.setText("Registro");
        mn_registrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_registromeActionPerformed(evt);
            }
        });
        mn_medico.add(mn_registrome);

        mn_mantenimiento.add(mn_medico);

        mn_centromedico.setText("Centro Medico");

        mn_consultacm.setText("Consulta");
        mn_consultacm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultacmActionPerformed(evt);
            }
        });
        mn_centromedico.add(mn_consultacm);

        mn_registrocm.setText("Registro");
        mn_registrocm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_registrocmActionPerformed(evt);
            }
        });
        mn_centromedico.add(mn_registrocm);

        mn_mantenimiento.add(mn_centromedico);

        mn_empleado.setText("Empleado");

        mn_consultaem.setText("Consulta");
        mn_consultaem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultaemActionPerformed(evt);
            }
        });
        mn_empleado.add(mn_consultaem);

        mn_registroem.setText("Registro");
        mn_registroem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_registroemActionPerformed(evt);
            }
        });
        mn_empleado.add(mn_registroem);

        mn_mantenimiento.add(mn_empleado);

        jMenuBar1.add(mn_mantenimiento);

        jMenu2.setBackground(new java.awt.Color(102, 102, 102));
        jMenu2.setForeground(new java.awt.Color(0, 0, 204));
        jMenu2.setText("Consulta");

        mn_consultafecha.setText("Fecha");
        mn_consultafecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultafechaActionPerformed(evt);
            }
        });
        jMenu2.add(mn_consultafecha);

        mn_consultaempleado.setText("Empleado");
        mn_consultaempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultaempleadoActionPerformed(evt);
            }
        });
        jMenu2.add(mn_consultaempleado);

        mn_consultaunidad.setText("Unidad");
        mn_consultaunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultaunidadActionPerformed(evt);
            }
        });
        jMenu2.add(mn_consultaunidad);

        mn_consultamotivo.setText("Motivo");
        mn_consultamotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultamotivoActionPerformed(evt);
            }
        });
        jMenu2.add(mn_consultamotivo);

        jMenuBar1.add(jMenu2);

        jMenu6.setBackground(new java.awt.Color(102, 102, 102));
        jMenu6.setForeground(new java.awt.Color(0, 0, 204));
        jMenu6.setText("Operaciones ");

        mn_registrodescansomedico.setText("Registro DM");
        mn_registrodescansomedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_registrodescansomedicoActionPerformed(evt);
            }
        });
        jMenu6.add(mn_registrodescansomedico);

        mn_consultadescansomedicodetallada.setText("Consulta DM Detallada");
        mn_consultadescansomedicodetallada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultadescansomedicodetalladaActionPerformed(evt);
            }
        });
        jMenu6.add(mn_consultadescansomedicodetallada);

        jMenuBar1.add(jMenu6);

        jMenu9.setBackground(new java.awt.Color(102, 102, 102));
        jMenu9.setForeground(new java.awt.Color(0, 0, 204));
        jMenu9.setText("Ayuda");
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_consultameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultameActionPerformed
JFrame consultamantemiento = new FrmConsultaMe();
consultamantemiento.setLocationRelativeTo(consultamantemiento);
consultamantemiento.setVisible(true);

   
    }//GEN-LAST:event_mn_consultameActionPerformed

    private void mn_registromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_registromeActionPerformed
    JFrame registromantenimiento  = new FrmRegistroEm();
    registromantenimiento.setLocationRelativeTo(registromantenimiento);
    registromantenimiento.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mn_registromeActionPerformed

    private void mn_consultacmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultacmActionPerformed
  JFrame consultacentromedico = new FrmConsultaCm();
  consultacentromedico.setLocationRelativeTo(consultacentromedico);
  consultacentromedico.setVisible(true);
        
    }//GEN-LAST:event_mn_consultacmActionPerformed

    private void mn_registrocmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_registrocmActionPerformed
    JFrame registrocentromedico =new FrmRegistroCm();
    registrocentromedico.setLocationRelativeTo(registrocentromedico);
    registrocentromedico.setVisible(true);
    }//GEN-LAST:event_mn_registrocmActionPerformed

    private void mn_consultaemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultaemActionPerformed
    JFrame consultaempleado = new FrmEmpleadoCon();
    consultaempleado.setLocationRelativeTo(consultaempleado);
    consultaempleado.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_consultaemActionPerformed

    private void mn_registroemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_registroemActionPerformed
     JFrame registroempleado = new FrmRegistroEm();
    registroempleado.setLocationRelativeTo(registroempleado);
    registroempleado.setVisible(true);
    }//GEN-LAST:event_mn_registroemActionPerformed

    private void mn_consultamotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultamotivoActionPerformed
        
    JFrame consultapormotivo = new FrmMotivo();
    consultapormotivo.setLocationRelativeTo(consultapormotivo);
    consultapormotivo.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_consultamotivoActionPerformed

    private void mn_consultafechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultafechaActionPerformed
    JFrame consultaporfecha = new FrmFecha();
    consultaporfecha.setLocationRelativeTo(consultaporfecha);
    consultaporfecha.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_consultafechaActionPerformed

    private void mn_consultaempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultaempleadoActionPerformed
    JFrame consultaporempleado = new FrmConsultaEm();
    consultaporempleado.setLocationRelativeTo(consultaporempleado);
    consultaporempleado.setVisible(true);
     

        // TODO add your handling code here:
    }//GEN-LAST:event_mn_consultaempleadoActionPerformed

    private void mn_consultaunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultaunidadActionPerformed
    JFrame consultaporunidad = new FrmUnidad();
    consultaporunidad.setLocationRelativeTo(consultaporunidad);
    consultaporunidad.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_mn_consultaunidadActionPerformed

    private void mn_registrodescansomedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_registrodescansomedicoActionPerformed
       JFrame registrodescansomedico = new FrmRegistrosDM();
       registrodescansomedico.setLocationRelativeTo(registrodescansomedico);
       registrodescansomedico.setVisible(true);
    }//GEN-LAST:event_mn_registrodescansomedicoActionPerformed

    private void mn_consultadescansomedicodetalladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultadescansomedicodetalladaActionPerformed
    JFrame consultadescansomedicodetallada = new FrmConsultasDM();
    consultadescansomedicodetallada.setLocationRelativeTo(consultadescansomedicodetallada);
    consultadescansomedicodetallada.setVisible(true);
        
    }//GEN-LAST:event_mn_consultadescansomedicodetalladaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mn_centromedico;
    private javax.swing.JMenuItem mn_consultacm;
    private javax.swing.JMenuItem mn_consultadescansomedicodetallada;
    private javax.swing.JMenuItem mn_consultaem;
    private javax.swing.JMenuItem mn_consultaempleado;
    private javax.swing.JMenuItem mn_consultafecha;
    private javax.swing.JMenuItem mn_consultame;
    private javax.swing.JMenuItem mn_consultamotivo;
    private javax.swing.JMenuItem mn_consultaunidad;
    private javax.swing.JMenu mn_empleado;
    private javax.swing.JMenu mn_mantenimiento;
    private javax.swing.JMenu mn_medico;
    private javax.swing.JMenuItem mn_registrocm;
    private javax.swing.JMenuItem mn_registrodescansomedico;
    private javax.swing.JMenuItem mn_registroem;
    private javax.swing.JMenuItem mn_registrome;
    // End of variables declaration//GEN-END:variables
}
