/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.CMedicoDao;
import Controlador.DescansoMedicoDao;
import Controlador.DiagnosticoDao;
import Controlador.EmpleadoDao;
import static Controlador.EmpleadoDao.obtenerEmpleadoxCodigo;
import Controlador.MedicoDao;
import Controlador.TipoLicenciaDao;
import Modelo.Centro_Medico;
import Modelo.Descanso_medico;
import Modelo.Diagnostico;
import Modelo.Empleado;
import Modelo.Medico;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ll
 */
public class FrmRegistrosDM extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrosDM
     */
    public FrmRegistrosDM() {
        initComponents();
        TipoLicenciaDao.llenarCombo(cboTipo_licencia);
        numeroAutogenerado();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        btnEmpleado = new javax.swing.JButton();
        txtEmpleadoNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtcFecha_inicio = new com.toedter.calendar.JDateChooser();
        dtcFecha_Fin = new com.toedter.calendar.JDateChooser();
        btnCalcular = new javax.swing.JButton();
        txtNumero_Dias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboTipo_licencia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        btnDiagnostico = new javax.swing.JButton();
        txtcodDiagnostico = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        txtCentro_medico = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        btnCentro_medico = new javax.swing.JButton();
        txtmediconombre = new javax.swing.JTextField();
        txtCentro_medico1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Descando Medico");

        jLabel1.setText("Registro de Nuevo Descanso Médico");

        jLabel2.setText("Nro");

        jLabel3.setText("Empleado");

        txtNumero.setEnabled(false);

        txtEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpleadoKeyReleased(evt);
            }
        });

        btnEmpleado.setText("...");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        txtEmpleadoNom.setEnabled(false);

        jLabel4.setText("Fecha Inicio");

        jLabel5.setText("Fecha Fin");

        dtcFecha_inicio.setDateFormatString("yyyy/MM/dd");

        dtcFecha_Fin.setDateFormatString("yyyy/MM/dd");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtNumero_Dias.setEnabled(false);

        jLabel6.setText("Tipo Licencia");

        jLabel7.setText("Diagnostico");

        cboTipo_licencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Observaciones");

        btnDiagnostico.setText("...");
        btnDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticoActionPerformed(evt);
            }
        });

        txtcodDiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodDiagnosticoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodDiagnosticoKeyTyped(evt);
            }
        });

        txtDiagnostico.setEnabled(false);

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        jLabel9.setText("Medico");

        jLabel10.setText("Centro Medico");

        txtMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicoKeyTyped(evt);
            }
        });

        txtCentro_medico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCentro_medicoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCentro_medicoKeyTyped(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMedico.setText("...");
        btnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoActionPerformed(evt);
            }
        });

        btnCentro_medico.setText("...");
        btnCentro_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentro_medicoActionPerformed(evt);
            }
        });

        txtmediconombre.setEnabled(false);

        txtCentro_medico1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(86, 86, 86)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCentro_medico, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCentro_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCentro_medico1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtmediconombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcodDiagnostico)
                                            .addComponent(cboTipo_licencia, 0, 128, Short.MAX_VALUE))
                                        .addComponent(dtcFecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel5)
                                            .addGap(33, 33, 33)
                                            .addComponent(dtcFecha_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(btnCalcular)
                                            .addGap(33, 33, 33)
                                            .addComponent(txtNumero_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btnDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDiagnostico))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEmpleadoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmpleadoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(6, 6, 6))
                                .addComponent(dtcFecha_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dtcFecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboTipo_licencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCalcular)
                        .addComponent(txtNumero_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtcodDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmediconombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCentro_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCentro_medico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCentro_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
                txtNumero.setText("");
		txtEmpleado.setText("");
		txtEmpleadoNom.setText("");
		dtcFecha_inicio.setDate(null);
		dtcFecha_Fin.setDate(null);
		txtNumero_Dias.setText("");
                txtDiagnostico.setText("");
                txtcodDiagnostico.setText("");
                txtObservacion.setText("");
                txtmediconombre.setText("");
                txtMedico.setText("");
                txtCentro_medico.setText("");
                txtCentro_medico1.setText("");
                numeroAutogenerado();
                TipoLicenciaDao.llenarCombo(cboTipo_licencia);
		
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int idcm = 0;
        
        if (cboTipo_licencia.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this,"Seleccione una opcion de Licencia");
        }
        
        for (Centro_Medico x: CMedicoDao.obtenerCentrosMedicosxRuc(txtCentro_medico.getText().trim())) {
            idcm=x.getIdcentro_medico();
        }
        
        String dm_fechaincio="";
        String dm_fechafin="";
        
        try {
		String formato = dtcFecha_inicio.getDateFormatString();
		Date date = dtcFecha_inicio.getDate();
		SimpleDateFormat sdf = new SimpleDateFormat(formato);
		dm_fechaincio=String.valueOf(sdf.format(date));
		String formato1 = dtcFecha_Fin.getDateFormatString();
		Date date1 = dtcFecha_Fin.getDate();
		SimpleDateFormat sdf1 = new SimpleDateFormat(formato);
		dm_fechafin=String.valueOf(sdf1.format(date1));
		System.out.println(dm_fechaincio);
		System.out.println(dm_fechafin);

        } catch (Exception e) {
             //JOptionPane.showMessageDialog(null, "Al menos elija una FECHA DE NACIMIENTO VALIDA ", "Error..!!", JOptionPane.ERROR_MESSAGE);

	}
        //Integer.parseInt(txtNumero.getText())
        Descanso_medico dm=new Descanso_medico(Integer.parseInt(txtNumero.getText()), txtEmpleado.getText(),dm_fechaincio , dm_fechafin, cboTipo_licencia.getSelectedIndex(), Integer.parseInt(txtcodDiagnostico.getText()), txtMedico.getText(), idcm, txtObservacion.getText(), Integer.parseInt(txtNumero_Dias.getText()));
        
        DescansoMedicoDao.RegistrarDM(dm);
        DescansoMedicoDao.alerta1(txtEmpleado.getText());
         numeroAutogenerado();       
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if(dtcFecha_inicio.getDate()!=null && dtcFecha_Fin.getDate()!=null) {
            txtNumero_Dias.setText(diferenciaEnDias2(dtcFecha_Fin.getDate(), dtcFecha_inicio.getDate())+1+"");
	}	
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        // TODO add your handling code here:
        FrmBUscarEmpleados busqueda=new FrmBUscarEmpleados();
        busqueda.setVisible(true);
                
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void txtEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpleadoKeyReleased
        // TODO add your handling code here:
        if (txtEmpleado.getText().trim().length()>5) {
            for (Empleado x:obtenerEmpleadoxCodigo(txtEmpleado.getText().trim())) {
               txtEmpleadoNom.setText(x.getEmp_nombre()+" "+x.getEmp_apellido());
            }
            
        }else txtEmpleadoNom.setText(null);
    }//GEN-LAST:event_txtEmpleadoKeyReleased

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
        // TODO add your handling code here:
        FrmBusquedaDiagnostico busqueda=new FrmBusquedaDiagnostico();
        busqueda.setVisible(true);
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void txtcodDiagnosticoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodDiagnosticoKeyReleased
        // TODO add your handling code here:
        if (txtcodDiagnostico.getText().trim().length()>0) {
            for (Diagnostico x:DiagnosticoDao.obtenerDiagnosticos(txtcodDiagnostico.getText().trim())) {
               txtDiagnostico.setText(x.getDescripcion());
            }
        }else{
            txtDiagnostico.setText(null);
        }
    }//GEN-LAST:event_txtcodDiagnosticoKeyReleased

    private void txtcodDiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodDiagnosticoKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if (!Character.isDigit(c)) {
                evt.consume();
                getToolkit().beep();
                
        }
    }//GEN-LAST:event_txtcodDiagnosticoKeyTyped

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
        // TODO add your handling code here:
        FrmBuscarMedico busqueda=new FrmBuscarMedico();
        busqueda.setVisible(true);
        
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void btnCentro_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentro_medicoActionPerformed
        // TODO add your handling code here:
        FrmBuscarCM busqueda=new FrmBuscarCM();
        busqueda.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnCentro_medicoActionPerformed

    private void txtCentro_medicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCentro_medicoKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();

        }
        
    }//GEN-LAST:event_txtCentro_medicoKeyTyped

    private void txtMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicoKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
            getToolkit().beep();

        }
    }//GEN-LAST:event_txtMedicoKeyTyped

    private void txtCentro_medicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCentro_medicoKeyReleased
        // TODO add your handling code here:
        if (txtCentro_medico.getText().trim().length()>10) {
            for (Centro_Medico x: CMedicoDao.obtenerCentrosMedicosxRuc(txtCentro_medico.getText().trim())) {
            txtCentro_medico1.setText(x.getCem_nombre());
        }
        }else{
            txtCentro_medico1.setText(null);
        }
    }//GEN-LAST:event_txtCentro_medicoKeyReleased

    private void txtMedicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicoKeyReleased
        // TODO add your handling code here:
        if (txtMedico.getText().trim().length()>4) {
            for (Medico x: MedicoDao.obtenerMedicosxCMP(txtMedico.getText().trim())) {
            txtmediconombre.setText(x.getEd_nombres()+" "+x.getMed_apellidos());
        }
        }else{
            txtmediconombre.setText(null);
        }
    }//GEN-LAST:event_txtMedicoKeyReleased
    
    protected void numeroAutogenerado() {
		txtNumero.setText(DescansoMedicoDao.obtenerDescansosMedicos().size()+1000000+1+"");
		System.out.println(DescansoMedicoDao.obtenerDescansosMedicos().size()+1000000+1);
    }
    
    public static int diferenciaEnDias2(Date fechaMayor, Date fechaMenor) {
		long diferenciaEn_ms = fechaMayor.getTime() - fechaMenor.getTime();
		long dias = diferenciaEn_ms / (1000 * 60 * 60 * 24);
		return (int) dias;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrosDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrosDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrosDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrosDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrosDM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCentro_medico;
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboTipo_licencia;
    private com.toedter.calendar.JDateChooser dtcFecha_Fin;
    private com.toedter.calendar.JDateChooser dtcFecha_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtCentro_medico;
    public static javax.swing.JTextField txtCentro_medico1;
    public static javax.swing.JTextField txtDiagnostico;
    public static javax.swing.JTextField txtEmpleado;
    public static javax.swing.JTextField txtEmpleadoNom;
    public static javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero_Dias;
    private javax.swing.JTextArea txtObservacion;
    public static javax.swing.JTextField txtcodDiagnostico;
    public static javax.swing.JTextField txtmediconombre;
    // End of variables declaration//GEN-END:variables
}
